### PR TITLE
Add browser Sandbox

### PR DESCRIPTION
**Pull request by posix4e**
- Download my example snap form https://drive.google.com/file/d/1UqtaFNLJ8B179NUG9K4xW3yaeKg7CnS4/view
- sudo snap connect brave:browser-sandbox (wont be neededc after publishing)

Run with sandbox

### CODE REVIEW

**Comment by posix4e** [comment]
Interestingly this does work if we install in devmode.

**Comment by posix4e** [comment]
Any updates here?

**Comment by posix4e** [comment]
Hey everyone?

**Comment by popey** [comment]
Aweomse work @posix4e - tested this on Ubuntu 18.04.

**Pull request merged**
